import assert from 'node:assert/strict'
import test from 'node:test'
import { createStudyQuestionFlow, generateStudyQuestionBatch, maxBatchAttempts, StudyQuestionAttemptError, type SafeStudyQuestion } from './generate-study-question'

const input = { concurso_id: 7, prova_id: 10, disciplina: 'D', assunto: 'A', subassunto: '', quantidade: 1 }
const question = (attempt: number, status: 'created' | 'duplicate' = 'created'): SafeStudyQuestion => ({ attempt, questao_id: 220 + attempt, status, disciplina: 'D', assunto: 'A', subassunto: null, banca: 'Cebraspe', dificuldade: 'media', enunciado: `Q${attempt}`, alternativas: { A: 'A', B: 'B', C: 'C', D: 'D', E: 'E' } })
const deps = (overrides = {}) => ({ authenticate: async () => true, resolveSelection: async () => ({ valid: true, board: 'Cebraspe' }), executeBatch: async () => generateStudyQuestionBatch(1, async (attempt) => question(attempt)), ...overrides })

test('quantidades e limites oficiais', () => { assert.equal(maxBatchAttempts(1), 1); assert.equal(maxBatchAttempts(5), 7); assert.equal(maxBatchAttempts(10), 13); assert.equal(maxBatchAttempts(2), 0) })
test('auth bloqueia antes do catálogo', async () => { let calls = 0; const flow = createStudyQuestionFlow(deps({ authenticate: async () => false, resolveSelection: async () => { calls++; return { valid: true, board: 'X' } } })); assert.deepEqual(await flow(input), { ok: false, code: 'AUTH_REQUIRED' }); assert.equal(calls, 0) })
test('quantidade inválida e seleção inválida são bloqueadas', async () => { const flow = createStudyQuestionFlow(deps()); assert.deepEqual(await flow({ ...input, quantidade: 2 }), { ok: false, code: 'INVALID_QUANTITY' }); assert.deepEqual(await flow({ ...input, prova_id: null }), { ok: false, code: 'INVALID_RAG_SELECTION' }) })
test('quantity 1, 5 e 10 completam sequencialmente', async () => { for (const quantity of [1, 5, 10]) { const order: number[] = []; const result = await generateStudyQuestionBatch(quantity, async (attempt) => { order.push(attempt); return question(attempt) }); assert.equal(result.status, 'complete'); assert.equal(result.generatedCount, quantity); assert.deepEqual(order, Array.from({ length: quantity }, (_, index) => index + 1)) } })
test('duplicata no meio continua', async () => { const result = await generateStudyQuestionBatch(5, async (attempt) => question(attempt, attempt === 3 ? 'duplicate' : 'created')); assert.equal(result.status, 'complete'); assert.equal(result.duplicates, 1); assert.equal(result.attempts, 5) })
test('rejeições estrutural/semântica continuam até max attempts', async () => { const result = await generateStudyQuestionBatch(5, async (attempt) => { if (attempt <= 3) throw new StudyQuestionAttemptError('REJECTED'); return question(attempt) }); assert.equal(result.status, 'partial'); assert.equal(result.attempts, 7); assert.equal(result.rejected, 3); assert.equal(result.generatedCount, 4) })
test('provider failure persistente interrompe preservando parcial', async () => { const result = await generateStudyQuestionBatch(5, async (attempt) => { if (attempt === 3) throw new StudyQuestionAttemptError('PROVIDER_FAILURE'); return question(attempt) }); assert.equal(result.status, 'partial'); assert.equal(result.generatedCount, 2); assert.equal(result.stoppedReason, 'PROVIDER_FAILURE') })
test('persistence failure interrompe lote', async () => { const result = await generateStudyQuestionBatch(5, async (attempt) => { if (attempt === 2) throw new StudyQuestionAttemptError('PERSISTENCE_FAILURE'); return question(attempt) }); assert.equal(result.status, 'partial'); assert.equal(result.generatedCount, 1); assert.equal(result.stoppedReason, 'PERSISTENCE_FAILURE') })
