-- FASE 12: histórico privado de conversas com IA.

create table if not exists public.conversas_estudo_ia (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  questao_id bigint not null references public.questoes_estudo(id) on delete cascade,
  pergunta text not null check (char_length(pergunta) between 1 and 2000),
  resposta text not null,
  fontes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists conversas_estudo_ia_usuario_questao_idx
  on public.conversas_estudo_ia(usuario_id, questao_id, created_at desc);

alter table public.conversas_estudo_ia enable row level security;
drop policy if exists "Usuário lê as próprias conversas de estudo" on public.conversas_estudo_ia;
create policy "Usuário lê as próprias conversas de estudo" on public.conversas_estudo_ia
  for select to authenticated using (usuario_id = (select auth.uid()));

grant select on public.conversas_estudo_ia to authenticated;
revoke insert, update, delete on public.conversas_estudo_ia from anon, authenticated;
revoke insert, update, delete on public.estudo_questao from anon, authenticated;
