-- Fase 17: edição administrativa transacional e trilha de auditoria.

create table if not exists public.admin_auditoria (
  id bigint generated by default as identity primary key,
  administrador_id uuid not null references auth.users(id),
  acao text not null,
  entidade text not null,
  entidade_id text not null,
  dados_anteriores jsonb,
  dados_novos jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists admin_auditoria_criado_idx
  on public.admin_auditoria (criado_em desc);

alter table public.admin_auditoria enable row level security;
drop policy if exists "Administradores leem auditoria" on public.admin_auditoria;
create policy "Administradores leem auditoria"
  on public.admin_auditoria for select to authenticated
  using (public.usuario_e_admin());

grant select on public.admin_auditoria to authenticated;
revoke insert, update, delete on public.admin_auditoria from anon, authenticated;

create or replace function public.admin_atualizar_questao(
  p_questao_id bigint,
  p_disciplina text,
  p_assunto text,
  p_subassunto text,
  p_banca text,
  p_dificuldade text,
  p_enunciado text,
  p_alternativa_a text,
  p_alternativa_b text,
  p_alternativa_c text,
  p_alternativa_d text,
  p_alternativa_e text,
  p_gabarito text,
  p_explicacao text
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := auth.uid();
  v_anterior jsonb;
  v_novo jsonb;
  v_gabarito text := upper(trim(p_gabarito));
begin
  if v_admin_id is null or not public.usuario_e_admin() then
    raise exception 'Acesso administrativo necessário' using errcode = '42501';
  end if;
  if p_questao_id is null or nullif(trim(p_disciplina), '') is null
    or nullif(trim(p_assunto), '') is null or nullif(trim(p_enunciado), '') is null then
    raise exception 'Campos obrigatórios ausentes' using errcode = '22023';
  end if;
  if v_gabarito not in ('A', 'B', 'C', 'D', 'E') then
    raise exception 'Gabarito inválido' using errcode = '22023';
  end if;
  if (v_gabarito = 'A' and nullif(trim(p_alternativa_a), '') is null)
    or (v_gabarito = 'B' and nullif(trim(p_alternativa_b), '') is null)
    or (v_gabarito = 'C' and nullif(trim(p_alternativa_c), '') is null)
    or (v_gabarito = 'D' and nullif(trim(p_alternativa_d), '') is null)
    or (v_gabarito = 'E' and nullif(trim(p_alternativa_e), '') is null) then
    raise exception 'A alternativa do gabarito não pode estar vazia' using errcode = '22023';
  end if;

  select to_jsonb(q) into v_anterior from public.questoes_estudo q where q.id = p_questao_id for update;
  if v_anterior is null then raise exception 'Questão não encontrada' using errcode = 'P0002'; end if;

  update public.questoes_estudo set
    disciplina = trim(p_disciplina), assunto = trim(p_assunto), subassunto = nullif(trim(p_subassunto), ''),
    banca = nullif(trim(p_banca), ''), dificuldade = nullif(trim(p_dificuldade), ''),
    enunciado = trim(p_enunciado), alternativa_a = nullif(trim(p_alternativa_a), ''),
    alternativa_b = nullif(trim(p_alternativa_b), ''), alternativa_c = nullif(trim(p_alternativa_c), ''),
    alternativa_d = nullif(trim(p_alternativa_d), ''), alternativa_e = nullif(trim(p_alternativa_e), ''),
    gabarito = v_gabarito, explicacao = nullif(trim(p_explicacao), '')
  where id = p_questao_id;

  select to_jsonb(q) into v_novo from public.questoes_estudo q where q.id = p_questao_id;
  insert into public.admin_auditoria (administrador_id, acao, entidade, entidade_id, dados_anteriores, dados_novos)
  values (v_admin_id, 'atualizar', 'questoes_estudo', p_questao_id::text, v_anterior, v_novo);
end;
$$;

revoke all on function public.admin_atualizar_questao(bigint, text, text, text, text, text, text, text, text, text, text, text, text, text) from public, anon;
grant execute on function public.admin_atualizar_questao(bigint, text, text, text, text, text, text, text, text, text, text, text, text, text) to authenticated;

notify pgrst, 'reload schema';
