-- FASE 6: respostas avulsas do banco de questões.
-- Revisar no SQL Editor do Supabase antes de aplicar. Este arquivo não é executado pelo app.

create table if not exists public.respostas_questoes (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  questao_id bigint not null references public.questoes_estudo(id) on delete cascade,
  alternativa_selecionada text not null check (alternativa_selecionada in ('A', 'B', 'C', 'D', 'E')),
  correta boolean not null,
  tempo_gasto integer check (tempo_gasto is null or tempo_gasto >= 0),
  created_at timestamptz not null default now()
);

create index if not exists respostas_questoes_usuario_created_idx
  on public.respostas_questoes (usuario_id, created_at desc);

create index if not exists respostas_questoes_usuario_questao_idx
  on public.respostas_questoes (usuario_id, questao_id);

alter table public.respostas_questoes enable row level security;

drop policy if exists "Usuário lê as próprias respostas" on public.respostas_questoes;
create policy "Usuário lê as próprias respostas"
  on public.respostas_questoes
  for select
  to authenticated
  using ((select auth.uid()) = usuario_id);

-- Não há policy de INSERT/UPDATE/DELETE. A gravação ocorre somente pela função abaixo,
-- impedindo que o cliente escolha o valor da coluna `correta`.

create or replace function public.responder_questao(
  p_questao_id bigint,
  p_alternativa text,
  p_tempo_gasto integer default null
)
returns table (
  resposta_id bigint,
  correta boolean,
  alternativa_correta text,
  explicacao text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_gabarito text;
  v_gabarito_normalizado text;
  v_explicacao text;
  v_resposta_id bigint;
  v_correta boolean;
  v_alternativa text := upper(trim(p_alternativa));
begin
  if v_usuario_id is null then
    raise exception 'Usuário não autenticado' using errcode = '42501';
  end if;

  if v_alternativa not in ('A', 'B', 'C', 'D', 'E') then
    raise exception 'Alternativa inválida' using errcode = '22023';
  end if;

  if p_tempo_gasto is not null and p_tempo_gasto < 0 then
    raise exception 'Tempo gasto inválido' using errcode = '22023';
  end if;

  select q.gabarito, q.explicacao
    into v_gabarito, v_explicacao
  from public.questoes_estudo q
  where q.id = p_questao_id;

  if not found then
    raise exception 'Questão não encontrada' using errcode = 'P0002';
  end if;

  v_gabarito_normalizado := upper(trim(v_gabarito));
  if v_gabarito_normalizado !~ '^[A-E]$' then
    v_gabarito_normalizado := substring(v_gabarito_normalizado from '([A-E])\s*$');
  end if;

  if v_gabarito_normalizado is null then
    raise exception 'Questão sem gabarito válido' using errcode = '22000';
  end if;

  v_correta := v_alternativa = v_gabarito_normalizado;

  insert into public.respostas_questoes (
    usuario_id, questao_id, alternativa_selecionada, correta, tempo_gasto
  ) values (
    v_usuario_id, p_questao_id, v_alternativa, v_correta, p_tempo_gasto
  )
  returning id into v_resposta_id;

  return query select v_resposta_id, v_correta, v_gabarito_normalizado, v_explicacao;
end;
$$;

revoke all on function public.responder_questao(bigint, text, integer) from public;
grant execute on function public.responder_questao(bigint, text, integer) to authenticated;

grant select on table public.respostas_questoes to authenticated;
