-- FASE 13: vínculo seguro entre usuário da aplicação e Telegram.

create table if not exists public.telegram_vinculos (
  usuario_id uuid primary key references auth.users(id) on delete cascade,
  chat_id bigint not null unique,
  username text,
  nome text,
  ativo boolean not null default true,
  vinculado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.telegram_codigos_vinculo (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  codigo text not null unique,
  expira_em timestamptz not null,
  utilizado_em timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists telegram_codigos_usuario_idx on public.telegram_codigos_vinculo(usuario_id, expira_em desc);
alter table public.telegram_vinculos enable row level security;
alter table public.telegram_codigos_vinculo enable row level security;

drop policy if exists "Usuário lê o próprio vínculo Telegram" on public.telegram_vinculos;
create policy "Usuário lê o próprio vínculo Telegram" on public.telegram_vinculos for select to authenticated using (usuario_id=(select auth.uid()));
drop policy if exists "Usuário lê os próprios códigos Telegram" on public.telegram_codigos_vinculo;
create policy "Usuário lê os próprios códigos Telegram" on public.telegram_codigos_vinculo for select to authenticated using (usuario_id=(select auth.uid()));
grant select on public.telegram_vinculos, public.telegram_codigos_vinculo to authenticated;
revoke insert, update, delete on public.telegram_vinculos, public.telegram_codigos_vinculo from anon, authenticated;

create or replace function public.gerar_codigo_vinculo_telegram()
returns table(codigo text, expira_em timestamptz)
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_codigo text; v_expira timestamptz := now() + interval '10 minutes';
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode='42501'; end if;
  delete from public.telegram_codigos_vinculo c where c.usuario_id=auth.uid() and c.utilizado_em is null;
  v_codigo := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  insert into public.telegram_codigos_vinculo(usuario_id,codigo,expira_em) values(auth.uid(),v_codigo,v_expira);
  return query select v_codigo,v_expira;
end; $$;

create or replace function public.desvincular_telegram()
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode='42501'; end if;
  delete from public.telegram_vinculos v where v.usuario_id=auth.uid();
end; $$;

create or replace function public.vincular_telegram_por_codigo(p_codigo text,p_chat_id bigint,p_username text,p_nome text)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_usuario uuid;
begin
  select c.usuario_id into v_usuario from public.telegram_codigos_vinculo c where c.codigo=upper(trim(p_codigo)) and c.utilizado_em is null and c.expira_em>now() for update;
  if v_usuario is null then raise exception 'Código inválido ou expirado' using errcode='22023'; end if;
  delete from public.telegram_vinculos where usuario_id=v_usuario or chat_id=p_chat_id;
  insert into public.telegram_vinculos(usuario_id,chat_id,username,nome) values(v_usuario,p_chat_id,nullif(p_username,''),nullif(p_nome,''));
  update public.telegram_codigos_vinculo set utilizado_em=now() where usuario_id=v_usuario and codigo=upper(trim(p_codigo));
  return v_usuario;
end; $$;

create or replace function public.desvincular_telegram_por_chat(p_chat_id bigint)
returns void language sql security definer set search_path=public,pg_temp as $$ delete from public.telegram_vinculos where chat_id=p_chat_id; $$;

revoke all on function public.gerar_codigo_vinculo_telegram(), public.desvincular_telegram(), public.vincular_telegram_por_codigo(text,bigint,text,text), public.desvincular_telegram_por_chat(bigint) from public;
grant execute on function public.gerar_codigo_vinculo_telegram(), public.desvincular_telegram() to authenticated;
grant execute on function public.vincular_telegram_por_codigo(text,bigint,text,text), public.desvincular_telegram_por_chat(bigint) to service_role;
