-- FASE TRT8-1: fundacao normalizada do conteudo programatico.
-- Nao migra dados, nao altera consumidores e nao remove conteudo_programatico.

begin;

create table public.conteudos_catalogo (
  id bigint generated by default as identity primary key,
  concurso_id bigint not null,
  disciplina text not null,
  assunto text,
  subassunto text,
  chave_canonica text not null,
  versao_normalizacao text not null default 'canonical-v1',
  ativo boolean not null default true,
  criado_em timestamptz not null default pg_catalog.now(),
  atualizado_em timestamptz not null default pg_catalog.now(),
  constraint conteudos_catalogo_concurso_id_fkey
    foreign key (concurso_id)
    references public.concursos(id)
    on update restrict
    on delete cascade,
  constraint conteudos_catalogo_disciplina_nao_vazia_check
    check (disciplina = btrim(disciplina) and disciplina <> ''),
  constraint conteudos_catalogo_assunto_normalizado_check
    check (assunto is null or (assunto = btrim(assunto) and assunto <> '')),
  constraint conteudos_catalogo_subassunto_normalizado_check
    check (subassunto is null or (subassunto = btrim(subassunto) and subassunto <> '')),
  constraint conteudos_catalogo_chave_canonica_check
    check (chave_canonica ~ '^[0-9a-f]{64}$'),
  constraint conteudos_catalogo_versao_normalizacao_check
    check (versao_normalizacao = 'canonical-v1'),
  constraint conteudos_catalogo_hierarquia_check
    check (subassunto is null or assunto is not null),
  constraint conteudos_catalogo_concurso_chave_key
    unique (concurso_id, chave_canonica),
  constraint conteudos_catalogo_id_concurso_key
    unique (id, concurso_id)
);

-- Necessaria para a FK composta que impede associacoes entre concursos.
-- id continua sendo a PK de provas; esta constraint apenas inclui concurso_id
-- na identidade referenciada pela associacao.
alter table public.provas
  add constraint provas_id_concurso_key unique (id, concurso_id);

create table public.prova_conteudos (
  prova_id bigint not null,
  conteudo_id bigint not null,
  concurso_id bigint not null,
  ativo boolean not null default true,
  disciplina_ordem integer,
  assunto_ordem integer,
  subassunto_ordem integer,
  ordem integer,
  origem text,
  criado_em timestamptz not null default pg_catalog.now(),
  atualizado_em timestamptz not null default pg_catalog.now(),
  constraint prova_conteudos_pkey primary key (prova_id, conteudo_id),
  constraint prova_conteudos_prova_concurso_fkey
    foreign key (prova_id, concurso_id)
    references public.provas(id, concurso_id)
    on update restrict
    on delete cascade,
  constraint prova_conteudos_conteudo_concurso_fkey
    foreign key (conteudo_id, concurso_id)
    references public.conteudos_catalogo(id, concurso_id)
    on update restrict
    on delete cascade,
  constraint prova_conteudos_ordens_check
    check (
      (disciplina_ordem is null or disciplina_ordem >= 0)
      and (assunto_ordem is null or assunto_ordem >= 0)
      and (subassunto_ordem is null or subassunto_ordem >= 0)
      and (ordem is null or ordem >= 0)
    )
);

-- A UNIQUE do catalogo ja atende buscas apenas por concurso_id.
create index conteudos_catalogo_concurso_ativo_idx
  on public.conteudos_catalogo (concurso_id, ativo);

-- A PK de prova_conteudos ja atende buscas apenas por prova_id.
create index prova_conteudos_conteudo_id_idx
  on public.prova_conteudos (conteudo_id);
create index prova_conteudos_prova_ativo_idx
  on public.prova_conteudos (prova_id, ativo);

alter table public.conteudos_catalogo enable row level security;
alter table public.prova_conteudos enable row level security;

create policy "Usuarios autenticados leem catalogo programatico"
  on public.conteudos_catalogo
  for select
  to authenticated
  using (true);

create policy "Usuarios autenticados leem conteudos das provas"
  on public.prova_conteudos
  for select
  to authenticated
  using (true);

revoke all on table public.conteudos_catalogo from public, anon, authenticated;
revoke all on table public.prova_conteudos from public, anon, authenticated;
revoke all on sequence public.conteudos_catalogo_id_seq from public, anon, authenticated;

grant select (
  id, concurso_id, disciplina, assunto, subassunto, ativo,
  criado_em, atualizado_em
) on public.conteudos_catalogo to authenticated;

grant select (
  prova_id, conteudo_id, concurso_id, ativo,
  disciplina_ordem, assunto_ordem, subassunto_ordem, ordem, origem,
  criado_em, atualizado_em
) on public.prova_conteudos to authenticated;

grant select, insert, update, delete on table public.conteudos_catalogo to service_role;
grant select, insert, update, delete on table public.prova_conteudos to service_role;
grant usage, select on sequence public.conteudos_catalogo_id_seq to service_role;

notify pgrst, 'reload schema';

commit;
