-- FASE 9: favoritos, marcações e sessões persistentes de revisão.
-- Revisar no SQL Editor do Supabase antes de aplicar.

create table if not exists public.questoes_favoritas (
  usuario_id uuid not null references auth.users(id) on delete cascade,
  questao_id bigint not null references public.questoes_estudo(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (usuario_id, questao_id)
);

create table if not exists public.questoes_revisao (
  usuario_id uuid not null references auth.users(id) on delete cascade,
  questao_id bigint not null references public.questoes_estudo(id) on delete cascade,
  motivo text not null default 'importante' check (motivo in ('importante', 'duvida')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (usuario_id, questao_id)
);

create table if not exists public.sessoes_revisao (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  titulo text not null,
  categoria text not null check (categoria in ('todas', 'erradas', 'favoritas', 'marcadas', 'baixo_desempenho')),
  status text not null default 'em_andamento' check (status in ('em_andamento', 'concluida')),
  created_at timestamptz not null default now(),
  concluida_at timestamptz
);

create table if not exists public.sessao_revisao_questoes (
  sessao_id bigint not null references public.sessoes_revisao(id) on delete cascade,
  questao_id bigint not null references public.questoes_estudo(id) on delete cascade,
  ordem integer not null,
  primary key (sessao_id, questao_id),
  unique (sessao_id, ordem)
);

alter table public.questoes_favoritas enable row level security;
alter table public.questoes_revisao enable row level security;
alter table public.sessoes_revisao enable row level security;
alter table public.sessao_revisao_questoes enable row level security;

drop policy if exists "Usuário lê favoritos próprios" on public.questoes_favoritas;
create policy "Usuário lê favoritos próprios" on public.questoes_favoritas for select to authenticated using (usuario_id = (select auth.uid()));
drop policy if exists "Usuário lê marcações próprias" on public.questoes_revisao;
create policy "Usuário lê marcações próprias" on public.questoes_revisao for select to authenticated using (usuario_id = (select auth.uid()));
drop policy if exists "Usuário lê sessões próprias" on public.sessoes_revisao;
create policy "Usuário lê sessões próprias" on public.sessoes_revisao for select to authenticated using (usuario_id = (select auth.uid()));
drop policy if exists "Usuário lê questões das sessões próprias" on public.sessao_revisao_questoes;
create policy "Usuário lê questões das sessões próprias" on public.sessao_revisao_questoes for select to authenticated
  using (exists (select 1 from public.sessoes_revisao s where s.id = sessao_id and s.usuario_id = (select auth.uid())));

grant select on public.questoes_favoritas, public.questoes_revisao, public.sessoes_revisao, public.sessao_revisao_questoes to authenticated;
revoke insert, update, delete on public.questoes_favoritas, public.questoes_revisao, public.sessoes_revisao, public.sessao_revisao_questoes from anon, authenticated;

create or replace function public.definir_questao_favorita(p_questao_id bigint, p_ativa boolean)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode = '42501'; end if;
  if p_ativa then insert into public.questoes_favoritas(usuario_id, questao_id) values(auth.uid(), p_questao_id) on conflict do nothing;
  else delete from public.questoes_favoritas where usuario_id = auth.uid() and questao_id = p_questao_id; end if;
end; $$;

create or replace function public.definir_questao_revisao(p_questao_id bigint, p_ativa boolean, p_motivo text default 'importante')
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode = '42501'; end if;
  if p_motivo not in ('importante','duvida') then raise exception 'Motivo inválido' using errcode = '22023'; end if;
  if p_ativa then insert into public.questoes_revisao(usuario_id, questao_id, motivo) values(auth.uid(), p_questao_id, p_motivo) on conflict(usuario_id, questao_id) do update set motivo = excluded.motivo, updated_at = now();
  else delete from public.questoes_revisao where usuario_id = auth.uid() and questao_id = p_questao_id; end if;
end; $$;

create or replace function public.listar_revisoes()
returns table (questao_id bigint, disciplina text, assunto text, subassunto text, enunciado text, errada boolean, favorita boolean, marcada boolean, baixo_desempenho boolean)
language plpgsql security definer set search_path = public, pg_temp stable as $$
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode = '42501'; end if;
  return query
  with tentativas as (
    select r.questao_id, r.correta from public.respostas_questoes r where r.usuario_id = auth.uid()
    union all
    select r.questao_id, r.correta from public.respostas_simulado r join public.simulados s on s.id = r.simulado_id where r.usuario_id = auth.uid() and s.status = 'concluido'
  ), desempenho as (
    select q.assunto from tentativas t join public.questoes_estudo q on q.id = t.questao_id group by q.assunto having count(*) >= 3 and avg(t.correta::integer) < 0.6
  ), ids as (
    select t.questao_id from tentativas t where not t.correta
    union select f.questao_id from public.questoes_favoritas f where f.usuario_id = auth.uid()
    union select m.questao_id from public.questoes_revisao m where m.usuario_id = auth.uid()
    union select q.id from public.questoes_estudo q join desempenho d on d.assunto = q.assunto
  )
  select q.id, q.disciplina::text, q.assunto::text, q.subassunto::text, q.enunciado::text,
    exists(select 1 from tentativas t where t.questao_id = q.id and not t.correta),
    exists(select 1 from public.questoes_favoritas f where f.usuario_id = auth.uid() and f.questao_id = q.id),
    exists(select 1 from public.questoes_revisao m where m.usuario_id = auth.uid() and m.questao_id = q.id),
    exists(select 1 from desempenho d where d.assunto = q.assunto)
  from ids join public.questoes_estudo q on q.id = ids.questao_id order by q.disciplina, q.assunto, q.id;
end;
$$;

create or replace function public.criar_sessao_revisao(p_categoria text default 'todas', p_limite integer default 15)
returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare v_id bigint; v_total integer;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode = '42501'; end if;
  if p_categoria not in ('todas','erradas','favoritas','marcadas','baixo_desempenho') then raise exception 'Categoria inválida' using errcode = '22023'; end if;
  if p_limite < 1 or p_limite > 50 then raise exception 'Limite inválido' using errcode = '22023'; end if;
  insert into public.sessoes_revisao(usuario_id, titulo, categoria) values(auth.uid(), 'Revisão de hoje — ' || p_limite || ' questões', p_categoria) returning id into v_id;
  insert into public.sessao_revisao_questoes(sessao_id, questao_id, ordem)
  select v_id, r.questao_id, row_number() over()::integer from public.listar_revisoes() r
  where p_categoria = 'todas' or (p_categoria='erradas' and r.errada) or (p_categoria='favoritas' and r.favorita) or (p_categoria='marcadas' and r.marcada) or (p_categoria='baixo_desempenho' and r.baixo_desempenho)
  order by random() limit p_limite;
  get diagnostics v_total = row_count;
  if v_total = 0 then delete from public.sessoes_revisao where id = v_id; raise exception 'Nenhuma questão disponível para esta revisão' using errcode = 'P0001'; end if;
  update public.sessoes_revisao set titulo = 'Revisão de hoje — ' || v_total || ' questões' where id = v_id;
  return v_id;
end; $$;

create or replace function public.concluir_sessao_revisao(p_sessao_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado' using errcode = '42501'; end if;
  update public.sessoes_revisao set status='concluida', concluida_at=now() where id=p_sessao_id and usuario_id=auth.uid();
  if not found then raise exception 'Sessão não encontrada' using errcode='P0002'; end if;
end; $$;

revoke all on function public.definir_questao_favorita(bigint, boolean), public.definir_questao_revisao(bigint, boolean, text), public.listar_revisoes(), public.criar_sessao_revisao(text, integer), public.concluir_sessao_revisao(bigint) from public;
grant execute on function public.definir_questao_favorita(bigint, boolean), public.definir_questao_revisao(bigint, boolean, text), public.listar_revisoes(), public.criar_sessao_revisao(text, integer), public.concluir_sessao_revisao(bigint) to authenticated;
