-- PROPOSTA RAG-2.7: contrato estrutural do RAG-V2.
-- Revisar antes de aplicar. Esta migration não ingere materiais, não gera
-- embeddings e não altera a função legada public.match_documents.

-- A tabela é o contrato central desta fase. Se já existir fora do histórico de
-- migrations, a execução deve falhar para revisão em vez de ocultar um schema
-- possivelmente incompatível com IF NOT EXISTS.
create table public.rag_ingestoes (
  id bigint generated by default as identity primary key,
  material_id bigint not null,
  embedding_provider text not null,
  embedding_model text not null,
  embedding_dimensions integer not null,
  chunking_version text not null,
  ingestion_version text not null,
  status text not null default 'processando',
  ativa boolean not null default false,
  total_chunks integer not null default 0,
  erro text,
  iniciado_em timestamptz not null default now(),
  concluido_em timestamptz,
  created_at timestamptz not null default now(),
  constraint rag_ingestoes_material_id_fkey
    foreign key (material_id)
    references public.materiais_concurso(id)
    on delete cascade,
  constraint rag_ingestoes_status_check
    check (status in ('processando', 'concluida', 'erro', 'cancelada')),
  constraint rag_ingestoes_embedding_dimensions_check
    check (embedding_dimensions > 0),
  constraint rag_ingestoes_total_chunks_check
    check (total_chunks >= 0)
);

alter table public.rag_ingestoes enable row level security;

-- Sem policy pública nesta fase. O pipeline futuro usará exclusivamente o
-- cliente server-side com service_role.
revoke all on table public.rag_ingestoes from public, anon, authenticated;
revoke all on sequence public.rag_ingestoes_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.rag_ingestoes to service_role;
grant usage, select on sequence public.rag_ingestoes_id_seq to service_role;

create index if not exists idx_rag_ingestoes_material_id
  on public.rag_ingestoes (material_id);

create index if not exists idx_rag_ingestoes_material_ativa_status
  on public.rag_ingestoes (material_id, ativa, status);

create unique index if not exists uq_rag_ingestoes_material_ativa
  on public.rag_ingestoes (material_id)
  where ativa = true;

-- Todas as colunas permanecem nullable para preservar os 695 chunks legados.
alter table public.documents
  add column if not exists ingestion_id bigint,
  add column if not exists content_hash text,
  add column if not exists embedding_provider text,
  add column if not exists embedding_model text,
  add column if not exists embedding_dimensions integer,
  add column if not exists ingestion_version text;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint c
    join pg_catalog.pg_class r on r.oid = c.conrelid
    join pg_catalog.pg_namespace n on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'documents'
      and c.conname = 'documents_ingestion_id_fkey'
  ) then
    alter table public.documents
      add constraint documents_ingestion_id_fkey
      foreign key (ingestion_id)
      references public.rag_ingestoes(id)
      on delete cascade;
  end if;
end;
$$;

create unique index if not exists uq_documents_ingestion_content_hash
  on public.documents (ingestion_id, content_hash)
  where ingestion_id is not null
    and content_hash is not null;

-- O vínculo passa a ser exigido para novos valores, sem apagar ou corrigir
-- referências históricas potencialmente inválidas. VALIDATE CONSTRAINT deve
-- ser executado apenas em fase posterior, após auditoria explícita do legado.
do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint c
    join pg_catalog.pg_class r on r.oid = c.conrelid
    join pg_catalog.pg_namespace n on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'questao_fontes'
      and c.conname = 'questao_fontes_document_id_fkey'
  ) then
    alter table public.questao_fontes
      add constraint questao_fontes_document_id_fkey
      foreign key (document_id)
      references public.documents(id)
      on delete set null
      not valid;
  end if;
end;
$$;

create or replace function public.match_documents_rag_v2(
  p_query_embedding public.vector(768),
  p_concurso_id bigint,
  p_prova_id bigint,
  p_match_count integer default 8,
  p_similarity_threshold double precision default null,
  p_disciplina text default null,
  p_assunto text default null,
  p_subassunto text default null
)
returns table (
  document_id bigint,
  material_id bigint,
  concurso_id bigint,
  prova_id bigint,
  content text,
  pagina integer,
  chunk_index integer,
  disciplina text,
  assunto text,
  subassunto text,
  arquivo_origem text,
  github_path text,
  ingestion_id bigint,
  embedding_model text,
  similarity double precision
)
language plpgsql
stable
security invoker
set search_path = pg_catalog, pg_temp
as $$
begin
  if p_query_embedding is null then
    raise exception 'p_query_embedding é obrigatório' using errcode = '22004';
  end if;

  if p_concurso_id is null then
    raise exception 'p_concurso_id é obrigatório' using errcode = '22004';
  end if;

  if p_match_count is null or p_match_count < 1 or p_match_count > 20 then
    raise exception 'p_match_count deve estar entre 1 e 20' using errcode = '22023';
  end if;

  if p_similarity_threshold is not null
     and (p_similarity_threshold < 0 or p_similarity_threshold > 1) then
    raise exception 'p_similarity_threshold deve estar entre 0 e 1' using errcode = '22023';
  end if;

  return query
  select
    d.id as document_id,
    m.id as material_id,
    d.concurso_id,
    m.prova_id,
    d.content,
    d.pagina,
    d.chunk_index,
    d.disciplina,
    d.assunto,
    d.subassunto,
    coalesce(d.arquivo_origem, m.arquivo_origem) as arquivo_origem,
    m.github_path,
    i.id as ingestion_id,
    d.embedding_model,
    1 - (d.embedding operator(public.<=>) p_query_embedding) as similarity
  from public.documents d
  join public.materiais_concurso m
    on m.id = d.material_id
  join public.rag_ingestoes i
    on i.id = d.ingestion_id
  where d.concurso_id = p_concurso_id
    and m.concurso_id = p_concurso_id
    and m.ativo = true
    and (
      (p_prova_id is null and m.prova_id is null)
      or
      (
        p_prova_id is not null
        and (
          m.prova_id is null
          or m.prova_id = p_prova_id
        )
      )
    )
    and i.status = 'concluida'
    and i.ativa = true
    and i.material_id = m.id
    and i.ingestion_version = 'rag-v2'
    and i.embedding_provider = 'google'
    and i.embedding_model = 'gemini-embedding-2'
    and i.embedding_dimensions = 768
    and d.ingestion_version = 'rag-v2'
    and d.embedding_provider = i.embedding_provider
    and d.embedding_model = i.embedding_model
    and d.embedding_dimensions = i.embedding_dimensions
    and d.embedding is not null
    and (p_disciplina is null or d.disciplina = p_disciplina)
    and (p_assunto is null or d.assunto = p_assunto)
    and (p_subassunto is null or d.subassunto = p_subassunto)
    and (
      p_similarity_threshold is null
      or 1 - (d.embedding operator(public.<=>) p_query_embedding) >= p_similarity_threshold
    )
  order by d.embedding operator(public.<=>) p_query_embedding
  limit p_match_count;
end;
$$;

-- CREATE FUNCTION concede EXECUTE a PUBLIC por padrão no PostgreSQL. A RPC
-- RAG-V2 é exclusivamente server-side e não fica disponível a clientes finais.
revoke all on function public.match_documents_rag_v2(
  public.vector,
  bigint,
  bigint,
  integer,
  double precision,
  text,
  text,
  text
) from public, anon, authenticated;

grant execute on function public.match_documents_rag_v2(
  public.vector,
  bigint,
  bigint,
  integer,
  double precision,
  text,
  text,
  text
) to service_role;

-- TODO RAG-V2: avaliar e criar índice HNSW somente após a primeira ingestão,
-- testes de retrieval e validação da estratégia/opclass. Esta migration
-- estrutural não cria nem remove índices vetoriais.

notify pgrst, 'reload schema';
